# Generated by Django 5.0.9 on 2026-07-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helppage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='body',
            field=models.TextField(blank=True, help_text='Markdown supported: **bold**, *italic*, [links](url), lists, etc.'),
        ),
    ]
